### PR TITLE
Default to postgres 12 when version is not specified.

### PR DESCRIPTION
**Pull request by jabrown85**
This will default Heroku CI postgres to version 12.0, which matches heroku's default.

The binaries for 12.0 have been uploaded for our current stacks.
```
» aws s3 ls s3://ci-database-binary/ --recursive
2017-12-11 08:46:07   23946277 cedar-14/postgresql-10.1.tgz
2018-08-23 16:44:00   24036511 cedar-14/postgresql-10.5.tgz
2019-03-08 10:51:42   24103825 cedar-14/postgresql-10.7.tgz
2019-03-08 10:12:27   25020693 cedar-14/postgresql-11.2.tgz
2019-10-08 08:35:49   27340103 cedar-14/postgresql-12.0.tgz
2018-01-03 10:38:44   21204116 cedar-14/postgresql-9.5.10.tgz
2019-03-08 11:25:00   22558864 cedar-14/postgresql-9.6.12.tgz
2017-05-12 04:15:16   22360892 cedar-14/postgresql-9.6.2.tgz
2017-10-12 05:56:23   22408647 cedar-14/postgresql-9.6.5.tgz
2017-11-28 02:04:42   22417231 cedar-14/postgresql-9.6.6.tgz
2018-06-21 03:39:21   22503580 cedar-14/postgresql-9.6.9.tgz
2018-08-23 16:33:23   24534014 heroku-16-build/postgresql-10.5.tgz
2019-03-08 11:03:54   24583944 heroku-16-build/postgresql-10.7.tgz
2019-03-08 10:25:44   25527761 heroku-16-build/postgresql-11.2.tgz
2019-10-08 08:48:59   27847885 heroku-16-build/postgresql-12.0.tgz
2019-03-08 11:37:55   23017157 heroku-16-build/postgresql-9.6.12.tgz
2017-05-12 04:15:16   22365202 heroku-16-build/postgresql-9.6.2.tgz
2018-08-23 17:54:30   22972836 heroku-16-build/postgresql-9.6.9.tgz
2017-12-11 08:33:58   24441809 heroku-16/postgresql-10.1.tgz
2018-06-11 11:39:14   24024763 heroku-16/postgresql-10.4.tgz
2018-08-23 16:24:41   24535136 heroku-16/postgresql-10.5.tgz
2019-03-08 10:58:06   24584917 heroku-16/postgresql-10.7.tgz
2019-03-08 10:19:05   25528015 heroku-16/postgresql-11.2.tgz
2019-10-08 08:42:45   27849136 heroku-16/postgresql-12.0.tgz
2018-01-03 11:03:29   21656374 heroku-16/postgresql-9.5.10.tgz
2019-03-08 11:31:28   23017902 heroku-16/postgresql-9.6.12.tgz
2017-05-12 04:15:16   22365202 heroku-16/postgresql-9.6.2.tgz
2017-10-12 07:20:01   22879885 heroku-16/postgresql-9.6.5.tgz
2017-11-28 02:23:01   22895314 heroku-16/postgresql-9.6.6.tgz
2018-06-11 11:44:58   22503762 heroku-16/postgresql-9.6.9.tgz
2018-08-23 15:33:22          0 heroku-18-build/
2018-08-23 15:59:38   26789211 heroku-18-build/postgresql-10.5.tgz
2019-03-08 11:16:54   26832474 heroku-18-build/postgresql-10.7.tgz
2019-03-08 10:40:50   27774748 heroku-18-build/postgresql-11.2.tgz
2019-10-08 09:04:39   30373120 heroku-18-build/postgresql-12.0.tgz
2019-03-08 11:51:55   24987872 heroku-18-build/postgresql-9.6.12.tgz
2018-08-23 17:45:17   24942917 heroku-18-build/postgresql-9.6.9.tgz
2018-08-23 15:33:15          0 heroku-18/
2018-08-23 15:40:09   26788395 heroku-18/postgresql-10.5.tgz
2019-03-08 11:10:28   26831154 heroku-18/postgresql-10.7.tgz
2019-03-08 10:33:12   27774814 heroku-18/postgresql-11.2.tgz
2019-10-08 08:56:46   30376451 heroku-18/postgresql-12.0.tgz
2019-03-08 11:44:53   24987547 heroku-18/postgresql-9.6.12.tgz
2018-08-23 16:53:15   24947543 heroku-18/postgresql-9.6.9.tgz
2019-03-08 09:23:17   27774654 postgresql-11.2.tgz
```

### CODE REVIEW

**Comment by jabrown85** [comment]
BLOCKED BY: Waiting on pg 12 to be GA before swapping the default version to match.

**Comment by bensymonds** [comment]
@jabrown85 Have you also got updating https://devcenter.heroku.com/articles/heroku-ci-in-dyno-databases on your list?

**Comment by jabrown85** [comment]
@bensymonds I went ahead and published the updated devcenter article since they can specify the version today. We don't document the default version so it wasn't blocked by this PR. I did add a note about updating that article in the instructions for building ci binaries.

**Comment by bensymonds** [comment]
Cool, nice one 👍

**Comment by jabrown85** [comment]
I went ahead and built the latest point versions of all supported major versions. (`9.6.15`, `10.10`, `11.5`). Here is an updated listing of versions in each stack directory on s3.

```
2017-12-11 08:46:07   23946277 cedar-14/postgresql-10.1.tgz
2019-10-08 10:09:17   24114786 cedar-14/postgresql-10.10.tgz
2018-08-23 16:44:00   24036511 cedar-14/postgresql-10.5.tgz
2019-03-08 10:51:42   24103825 cedar-14/postgresql-10.7.tgz
2019-03-08 10:12:27   25020693 cedar-14/postgresql-11.2.tgz
2019-10-08 09:37:39   25038599 cedar-14/postgresql-11.5.tgz
2019-10-08 08:35:49   27340103 cedar-14/postgresql-12.0.tgz
2018-01-03 10:38:44   21204116 cedar-14/postgresql-9.5.10.tgz
2019-03-08 11:25:00   22558864 cedar-14/postgresql-9.6.12.tgz
2019-10-08 10:41:27   22569530 cedar-14/postgresql-9.6.15.tgz
2017-05-12 04:15:16   22360892 cedar-14/postgresql-9.6.2.tgz
2017-10-12 05:56:23   22408647 cedar-14/postgresql-9.6.5.tgz
2017-11-28 02:04:42   22417231 cedar-14/postgresql-9.6.6.tgz
2018-06-21 03:39:21   22503580 cedar-14/postgresql-9.6.9.tgz
2019-10-08 10:21:01   24590131 heroku-16-build/postgresql-10.10.tgz
2018-08-23 16:33:23   24534014 heroku-16-build/postgresql-10.5.tgz
2019-03-08 11:03:54   24583944 heroku-16-build/postgresql-10.7.tgz
2019-03-08 10:25:44   25527761 heroku-16-build/postgresql-11.2.tgz
2019-10-08 09:49:46   25536685 heroku-16-build/postgresql-11.5.tgz
2019-10-08 08:48:59   27847885 heroku-16-build/postgresql-12.0.tgz
2019-03-08 11:37:55   23017157 heroku-16-build/postgresql-9.6.12.tgz
2019-10-08 10:53:12   23026900 heroku-16-build/postgresql-9.6.15.tgz
2017-05-12 04:15:16   22365202 heroku-16-build/postgresql-9.6.2.tgz
2018-08-23 17:54:30   22972836 heroku-16-build/postgresql-9.6.9.tgz
2017-12-11 08:33:58   24441809 heroku-16/postgresql-10.1.tgz
2019-10-08 10:15:01   24589875 heroku-16/postgresql-10.10.tgz
2018-06-11 11:39:14   24024763 heroku-16/postgresql-10.4.tgz
2018-08-23 16:24:41   24535136 heroku-16/postgresql-10.5.tgz
2019-03-08 10:58:06   24584917 heroku-16/postgresql-10.7.tgz
2019-03-08 10:19:05   25528015 heroku-16/postgresql-11.2.tgz
2019-10-08 09:43:44   25536186 heroku-16/postgresql-11.5.tgz
2019-10-08 08:42:45   27849136 heroku-16/postgresql-12.0.tgz
2018-01-03 11:03:29   21656374 heroku-16/postgresql-9.5.10.tgz
2019-03-08 11:31:28   23017902 heroku-16/postgresql-9.6.12.tgz
2019-10-08 10:46:53   23025710 heroku-16/postgresql-9.6.15.tgz
2017-05-12 04:15:16   22365202 heroku-16/postgresql-9.6.2.tgz
2017-10-12 07:20:01   22879885 heroku-16/postgresql-9.6.5.tgz
2017-11-28 02:23:01   22895314 heroku-16/postgresql-9.6.6.tgz
2018-06-11 11:44:58   22503762 heroku-16/postgresql-9.6.9.tgz
2018-08-23 15:33:22          0 heroku-18-build/
2019-10-08 10:34:16   26850918 heroku-18-build/postgresql-10.10.tgz
2018-08-23 15:59:38   26789211 heroku-18-build/postgresql-10.5.tgz
2019-03-08 11:16:54   26832474 heroku-18-build/postgresql-10.7.tgz
2019-03-08 10:40:50   27774748 heroku-18-build/postgresql-11.2.tgz
2019-10-08 10:02:49   27786922 heroku-18-build/postgresql-11.5.tgz
2019-10-08 09:04:39   30373120 heroku-18-build/postgresql-12.0.tgz
2019-03-08 11:51:55   24987872 heroku-18-build/postgresql-9.6.12.tgz
2019-10-08 11:07:18   25000141 heroku-18-build/postgresql-9.6.15.tgz
2018-08-23 17:45:17   24942917 heroku-18-build/postgresql-9.6.9.tgz
2018-08-23 15:33:15          0 heroku-18/
2019-10-08 10:27:19   26847403 heroku-18/postgresql-10.10.tgz
2018-08-23 15:40:09   26788395 heroku-18/postgresql-10.5.tgz
2019-03-08 11:10:28   26831154 heroku-18/postgresql-10.7.tgz
2019-03-08 10:33:12   27774814 heroku-18/postgresql-11.2.tgz
2019-10-08 09:56:14   27785594 heroku-18/postgresql-11.5.tgz
2019-10-08 08:56:46   30376451 heroku-18/postgresql-12.0.tgz
2019-03-08 11:44:53   24987547 heroku-18/postgresql-9.6.12.tgz
2019-10-08 11:00:22   25001723 heroku-18/postgresql-9.6.15.tgz
2018-08-23 16:53:15   24947543 heroku-18/postgresql-9.6.9.tgz
```

**Comment by tbalthazar** [comment]
New patch versions of Postgres have been published in the mean time.
Closing in favor of #31.

**Pull request closed without merging**
