### PR TITLE
Add PG13

### PR DESCRIPTION
**Pull request by beanieboi**
this adds postgres 13

### CODE REVIEW

**Review by edmorley — COMMENTED** [review]
Could you add the new version to `.travis.yml` too? :-)

**Comment by beanieboi** [comment]
> Could you add the new version to `.travis.yml` too? :-)

whops. missed that one. should I do cedar-14 as well or only heroku-16 and newer?

**Review by jabrown85 — APPROVED** [review]
Approved. Building binaries now.

**Comment by edmorley** [comment]
I wouldn't bother for Cedar-14, as PG13 is not the default version for this buildpack, and the Cedar-14 build system is being sunset in Jan.

**Pull request merged**
