### PR TITLE
PostgreSQL 15

### PR DESCRIPTION
**Pull request by kbarber**
Prior art: https://github.com/heroku/heroku-buildpack-ci-postgresql/pull/56

This is more in prep for release, so I haven't changed the default version yet.

### CODE REVIEW

**Comment by edmorley** [comment]
Docs on how to trigger building new binaries using the the GitHub Action automation are here, in case it helps:
https://github.com/heroku/engineering-docs/blob/master/components/heroku-buildpack-ci-postgresql/update-version.md#upload-new-postgres-versions-to-s3-via-github-action

**Comment by kbarber** [comment]
> Docs on how to trigger building new binaries using the GitHub Action automation are here, in case it helps: https://github.com/heroku/engineering-docs/blob/master/components/heroku-buildpack-ci-postgresql/update-version.md#upload-new-postgres-versions-to-s3-via-github-action

@edmorley I've requested 15.2 but it looks like I need approval: https://github.com/heroku/heroku-buildpack-ci-postgresql/actions/runs/4183148719

**Comment by edmorley** [comment]
I've marked the binary job as approved, is running now

**Comment by kbarber** [comment]
Thanks @edmorley looks like we're passing now.

**Review by PaulyFleming — APPROVED** [review]

**Comment by kbarber** [comment]
@edmorley what are the next steps from here?

**Comment by edmorley** [comment]
@kbarber This buildpack is owned by the Builds team - I just happened to be repo-watching (since the languages team has made changes to it from time to time eg when adding/removing supported stacks) so left a drive-by review. Sorry if that added confusion! I'll request review from them now, since whilst I'm sure they would probably be fine with me reviewing/merging/releasing, they'll be the ones that get paged if there are any Heroku CI support tickets that arise :-)

**Comment by kbarber** [comment]
@jabrown85 I've tested this (you can possibly see the test here): https://dashboard.heroku.com/pipelines/a49257e7-9f62-4b92-9842-b44a771a61ea/tests/3 ... it looks like its working okay, connecting via psql and dumping out the correct version for select version():

```
-----> Building on the Heroku-20 stack
-----> Fetching https://github.com/heroku/heroku-buildpack-ci-postgresql#postgresql-15 buildpack...
       buildpack downloaded
-----> Auto detecting buildpacks...
       no buildpacks detected
-----> Postgresql app detected
       Using postgresql version: 15.2
       Using stack version: heroku-20
-----> Fetching and vendoring postgresql into slug
-----> Initializing database
       The files belonging to this database system will be owned by user "u40993".
       This user must also own the server process.
       
       The database cluster will be initialized with locale "en_US.UTF-8".
       The default text search configuration will be set to "english".
       
       Data page checksums are disabled.
       
       creating directory /app/.indyno/vendor/postgresql/data ... ok
       creating subdirectories ... ok
       selecting dynamic shared memory implementation ... posix
       selecting default max_connections ... 100
       selecting default shared_buffers ... 128MB
       selecting default time zone ... Etc/UTC
       creating configuration files ... ok
       running bootstrap script ... ok
       performing post-bootstrap initialization ... ok
initdb:       syncing data to disk ... ok
       
 warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
       
       Success. You can now start the database server using:
       
           pg_ctl -D /app/.indyno/vendor/postgresql/data -l logfile start
       
       waiting for server to start.... done
       server started
       CREATE ROLE
-----> Creating heroku_ext schema for extensions
       CREATE SCHEMA
-----> Copying .profile.d/00-pg-path.sh to add postgresql binaries to PATH
-----> Postgresql done
-----> No test-setup command provided. Skipping.
```

```
-----> Running test command `script/cibuild`...
                                                version                                                
-------------------------------------------------------------------------------------------------------
 PostgreSQL 15.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)
-----> test command `script/cibuild` completed successfully
```

**Comment by jabrown85** [comment]
I pushed a new version @kbarber! Thanks for the contribution 😄

**Pull request merged**
