### PR TITLE
update postgres versions

### PR DESCRIPTION
**Pull request by subakva**
updates postgres versions to the latest patch versions and changes the default to 14 to match the default for our add-ons

### CODE REVIEW

**Comment by subakva** [comment]
@jabrown85 👋 This is the PR that got me poking around in the github actions to build pg versions. (Sorry about the noise...) This isn't critical, but it would be nice to get the CI versions in sync with the latest pg versions.

**Comment by jabrown85** [comment]
Ah, gotcha. I'll try and get this fixed up https://github.com/heroku/heroku-buildpack-ci-postgresql/pull/59 is currently blocking CI. Then I'll see about kicking off an action for all the versions you've updated and go from there.

**Comment by jabrown85** [comment]
After your version file update...I'm running the binary generation again 😛

**Comment by subakva** [comment]
@jabrown85 I rebased this morning, but didn't update the versions! I hope that didn't disrupt things too much. Thank you for helping with this!

**Comment by jabrown85** [comment]
@subakva it looks like you might've on accident?

https://github.com/heroku/heroku-buildpack-ci-postgresql/commit/29295d28636a00ec63f34bfe29f689081e2ecf55 has:

`9.6.24;10.22;11.17;12.12;13.8;14.5`

That is what I kicked off earlier today.

Current commit has:

`9.6.24;10.21;11.16;12.11;13.7;14.4`

I thought the downgrade was on purpose and so the CI is running with the latest on this branch. Not a big deal either way, once all the versions are built they'll all be available for us.

**Comment by subakva** [comment]
Ugh. Yes, that was an accident. :( I want them to be on the newest versions. I will update it.

**Comment by jabrown85** [comment]
@subakva Once you update this branch, can you do a sanity check using this branch for a couple of the most common cases?

- `POSTGRESQL_VERSION` unset == `14.4`
- `POSTGRESQL_VERSION=13` == `13.7`

Since the GitHub action ran successfully earlier, the binaries for these later versions should already be available for use 😄

**Comment by subakva** [comment]
@jabrown85 Absolutely!

**Comment by subakva** [comment]
@jabrown85 I checked all upgraded versions: 9.6, 10, 11, 12, 13, and 14.

**Review by jabrown85 — APPROVED** [review]

**Comment by jabrown85** [comment]
Thanks @subakva! I just released an updated buildpack version with these new defaults.

**Pull request merged**
