### PR TITLE
swap heroku-18 for heroku-24

### PR DESCRIPTION
**Pull request by jason-salesforce**
Adding Heroku-24 and removing a lingering Heroku-18 reference.

### CODE REVIEW

**Review by bchen528 — APPROVED** [review]

**Review by edmorley — APPROVED** [review]
Thank you - this looks great!

(CI is now passing upon retrigger, now that the builds have finished in https://github.com/heroku/heroku-buildpack-ci-postgresql/actions/runs/9210966618)

**Comment by edmorley** [comment]
@jason-salesforce Would you like me to publish this to the buildpack registry now?

**Comment by jason-salesforce** [comment]
@edmorley yes please!

**Comment by edmorley** [comment]
Published:

```
$ h buildpacks:publish heroku/ci-postgresql master
Publishing buildpack heroku/ci-postgresql... done
Publishing buildpack was successful

$ h buildpacks:versions heroku/ci-postgresql | head -n 4
 Version Released At              Status
 ─────── ──────────────────────── ─────────
 22      2024-05-23T17:37:04.798Z published
 21      2024-04-29T20:29:52.381Z published
```

**Pull request merged**
